### ISSUE TITLE
Add Agda 2.6.2

### ISSUE THREAD

**Issue by ice1000** [codewars/runner#10]
Please complete the following information:

- Name: Agda
- Version: 2.6.2
- Release Note/Changelog: https://github.com/agda/agda/blob/master/doc/release-notes/2.6.1.md and https://github.com/agda/agda/blob/master/doc/release-notes/2.6.2.md

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Created https://github.com/codewars/agda

Change https://github.com/codewars/agda/blob/main/Dockerfile to install the version you want and open a PR.

You can build the image locally with `docker build -t ghcr.io/codewars/agda:latest .`. Try example with `bin/run` (no output for correct solution).

**Comment by ice1000** [comment]
See https://github.com/codewars/agda/pull/1 @kazk

Is it possible to build this without docker installed? Like is there a CI for testing? I only have a poor laptop

**Comment by kazk** [comment]
Added basic CI and it passed. Took 51 minutes to build the image.

**Comment by kazk** [comment]
I should be able to deploy it tomorrow.

**Comment by kazk** [comment]
Deployed if you want to try. I'll run a script to update compatible kata later.

**Comment by kazk** [comment]
33 kata failed to update. See https://github.com/codewars/content-issues/wiki/List-of-Agda-Kata-to-Update

**Comment by monadius** [comment]
The new Agda version is slower than Agda 2.6.0. It is impossible to update some kata to 2.6.2 because they time out. I suggest to increase the timeout to 20 seconds.

**Comment by Kacarott** [comment]
I worry that 20 seconds might still not be enough. Even a single import `import Data.Integer` with nothing else already times out in 2.6.2.

**Comment by kazk** [comment]
Is 2.6.2 known to be much slower than 2.6.0? Maybe something is wrong with our setup?

I don't know anything about Agda, so I'll need help. The image is maintained at https://github.com/codewars/agda

Some thoughts:

- The current base image is the same as the one used in 2.6.0 and is ancient. Perhaps a newer version is faster. The command used to install didn't work in newer version because of `cabal` version difference.
- The current base image is Alpine, which uses musl instead of glibc. Sometimes it's slower. Try ubuntu/debian images. I wouldn't mind using anything as long as the final image is not huge.
- Any compiler flags?

**Comment by monadius** [comment]
On my machine (Ubuntu 22.04) I get the following results for an Agda file which loads `Data.Integer`:

1) Agda 2.6.2.2 without Docker: 9.7 seconds
2) `ghcr.io/codewars/agda:latest`: 12.1 seconds
3) `ghcr.io/codewars/agda:2.6.0`:  4.8 seconds

**Comment by ice1000** [comment]
> On my machine (Ubuntu 22.04) I get the following results for an Agda file which loads `Data.Integer`:
> 
> 1. Agda 2.6.2.2 without Docker: 9.7 seconds
> 2. `ghcr.io/codewars/agda:latest`: 12.1 seconds
> 3. `ghcr.io/codewars/agda:2.6.0`:  4.8 seconds

I guess it's because `Data.Integer` is now much larger. Maybe we should start trying `Data.Integer.Base` or something.
