### ISSUE TITLE
Rust: Enable "rand" feature on the "num" crate

### ISSUE THREAD

**Issue by Minoru** [codewars/runner#102]
**Is your feature request related to a problem? Please describe.**
I'm translating [this kata](https://www.codewars.com/kata/5eb9a92898f59000184c8e34/) to Rust, and I need to generate large random integers for testing. The `num` crate contains a `BigUint` type which fits my purpose, and even has [a `RandBigInt` trait](https://docs.rs/num/0.3.1/num/bigint/trait.RandBigInt.html) that generates random numbers — but that trait is only available if the "rand" feature is enabled on the "num" crate, which CodeWars doesn't do.

**Describe the solution you'd like**
I'd like CodeWars to add the following to their Cargo.toml:

```toml
[dependencies.num]
features = [ "rand" ]
```

**Describe alternatives you've considered**
It's possible to copy the code from the num crate into each test suite, but doing so for each kata with big numbers would be bothersome.

**Comment by hobovsky** [comment]
Potential workaround would be to generate a series of `u32` digits and use something what documentation describes as `pub fn new(digits: Vec<u32>) -> BigUint` or `pub fn from_slice(slice: &[u32]) -> BigUint`. That's how java generates random BigInteres. Or generate an array of random bytes and use them to instantiate big int with `from_bytes_be` or `from_bytes_le`.

**Comment by kazk** [comment]
I'll wait until https://github.com/rust-num/num-bigint/pull/185 is released.

**Comment by kazk** [comment]
I'll add Rust 1.50 instead of enabling this in 1.49. I'll also change to stop concatenating the preloaded code and use `preloaded.rs`. This will minimize the awkwardness, and it'll be easier for users to solve locally.

This will break existing solutions for kata using preloaded because the solution must include `mod preloaded;` now. But it's better to do this now considering how Rust is getting more and more popular on Codewars. (If this is turns out to be a **huge** problem, I'll consider letting the runner prepend `mod preloaded;` to affected solutions, but I'd rather not.)

There are currently 48 Rust kata using preloaded, but it looks like some of them can stop using preloaded. Examples:

- own random function (we didn't have `rand` at first)
- small test helper (can duplicate the code in sample tests)
- reference solution (should be in submission tests)

**Comment by kazk** [comment]
Turns out we can avoid breaking in many kata. See https://github.com/codewars/content-issues/wiki/List-of-Rust-Kata-to-Update

@imjasonmiller can you help?

**Comment by imjasonmiller** [comment]
Sure @kazk! I'll have a look at the kata tomorrow, as it's past midnight here.

**Comment by kazk** [comment]
Deployed 1.50 having `num` with `rand` feature. I haven't updated compatible kata yet.

**Comment by kazk** [comment]
Updated most Rust kata to 1.50. See https://github.com/codewars/content-issues/wiki/List-of-Rust-Kata-to-Update for the remaining.

**Comment by imjasonmiller** [comment]
I've been able to edit some, but I think I need to raise an issue in order to unlock editing the others? Some of the test cases are unfortunately locked as well, but this unlocks at 10K, right?
