### ISSUE TITLE
Racket 8.1 is extremely slower than 7.2 for big numbers

### ISSUE THREAD

**Issue by kazk** [codewars/runner#129]
Racket 8.1 was added, but a performance issue was found for big numbers.

https://github.com/codewars/runner/issues/127#issuecomment-867299364

It's reproducible even when executed on the host, so it's not a problem with Code Runner or containers. This issue will be used to keep track of any findings.

**Comment by Voileexperiments** [comment]
Apparently Racket default VM implementation has been changed since 8.0:

https://docs.racket-lang.org/guide/performance.html (at 19.2)

On CW environment `(system-type 'vm)` and `(system-type 'gc)` returns `'racket` and `'3m` in 7.2, and `'chez-scheme` and `'cs` in 8.1.

Then there are sections about how optimizations work on different VM implementations, which includes some passages about numbers, but I don't see anything mentioned about big exact integers (`fixnum` are small exact integers).

**Comment by s-cerevisiae** [comment]
Racket BC is still provided alongside with CS versions which is the default since 8.0.

On the millionth fibonacci kata, with Racket 8.1 BC I get:
```
cpu time: 760 real time: 758 gc time: 8
```
With Racket CS:
```
cpu time: 6368 real time: 6371 gc time: 144
```
So switch to BC version of the image may be a temporary solution.

**Comment by kazk** [comment]
I guess BC uses GMP, but CS doesn't? From the commit (https://github.com/racket/racket/commit/50a2cb32cb9dc1fdae260f9c1766c96609b411fb) that optimizes multiplications:

> Current Racket CS:
> cpu time: 19135 real time: 19137 gc time: 372
> cpu time: 33416 real time: 33418 gc time: 463
>
> Current Racket BC (GMP is really fast):
> cpu time: 1465 real time: 1465 gc time: 51
> cpu time: 3661 real time: 3659 gc time: 3
>
> This PR:
> cpu time: 6173 real time: 6172 gc time: 168
> cpu time: 17846 real time: 17847 gc time: 377

---

> In general, Racket programs should run the same in all variants. Furthermore, the performance characteristics of Racket program should be similar in the [CS](https://docs.racket-lang.org/guide/performance.html#%28tech._c%29) and [BC](https://docs.racket-lang.org/guide/performance.html#%28tech._bc%29) implementations. The cases where a program may depend on the implementation will typically **involve interactions with foreign libraries**; in particular, the Racket C API described in [Inside: Racket C API](https://docs.racket-lang.org/inside/index.html) is different for the [CS](https://docs.racket-lang.org/guide/performance.html#%28tech._c%29) implementation versus the [BC](https://docs.racket-lang.org/guide/performance.html#%28tech._bc%29) implementation.

**Comment by kazk** [comment]
@s-cerevisiae

> So switch to BC version of the image may be a temporary solution.

How can I do that? `racket --help` doesn't seem to have any options for it.

**Comment by s-cerevisiae** [comment]
@kazk 
Sorry for being unclear. Racket BC and CS are different implementations, so by "switch" I meant install another version of it.
This is the BC installer: https://mirror.racket-lang.org/installers/8.1/racket-minimal-8.1-x86_64-linux-bc.sh

PS: IMO it would be better to keep both `8.1 BC` and `8.1 CS` as language options instead of replacing CS with BC, since CS is now the default implementation and it outperforms BC most of the time (except for bignums...).

**Comment by kazk** [comment]
Deployed Racket 8.1 BC
