### ISSUE TITLE
Add Elixir 1.15

### ISSUE THREAD

**Issue by iacore** [codewars/runner#132]
Please complete the following information:

- Name: Elixir
- Version: 1.15
- Release Note/Changelog: https://github.com/elixir-lang/elixir/releases

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by MobulaKuhlii** [comment]
most significant changes are with `1.12.0`, namely some additions to standard library, as well as some minor improvements of ExUnit, but Erlang's OTP also requires updating since current version is `20` (and as mentioned in linked release notes since `24` it supports JIT compilation and has performance improvements)

**Comment by kazk** [comment]
Added Elixir 1.15. 3 kata need updates to enable it. See https://github.com/codewars/content-issues/wiki/List-of-Elixir-Kata-to-Update
