### ISSUE TITLE
Test output panel shows no feedback when Scala test suite crashes

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#139]
When Scala test suite crashes with some fatal error like `StackOverflowError` or `OutOfMemoryError`, test output breaks abruptly and provides no meaningful feedback.

### To Reproduce

This kumite provides an example of `StackOverflowError`: https://www.codewars.com/kumite/5f2d79c341132d0023c94da6?sel=5f2d79c341132d0023c94da6
Here you can see results of `OutOfMemoryError`: https://www.codewars.com/kumite/61199307356703004a4d04eb?sel=61199307356703004a4d04eb

### Additional context

The issue was first mentioned in #69  and this post by @kazk has some analysis of the problem: https://github.com/codewars/runner/issues/69#issuecomment-670643165

**Comment by kazk** [comment]
`StackOverflowError`

![image](https://user-images.githubusercontent.com/639336/129494613-0322f23b-8433-4f1a-b201-073e6fb4fd3c.png)

`OutOfMemoryError`

![image](https://user-images.githubusercontent.com/639336/129494645-8cbd3d6a-38ea-4dbd-9289-48994b32aba5.png)

For "shows no feedback", the crashed test case has nothing to show because it crashed, so the best we can do is to make that more clear by adding some fallback failure message.

For misleading `Failed: 0`, I had originally fixed it in #69 (https://github.com/codewars/runner/issues/69#issuecomment-840926428) using some option used by Qualified's contents, but had to revert it because of compatibility issues (https://github.com/codewars/runner/issues/69#issuecomment-841158413).

**Comment by hobovsky** [comment]
> For "shows no feedback", the crashed test case has nothing to show because it crashed, so the best we can do is to make that more clear by adding some fallback failure message.

The thing is that other languages I know do not break the output this abruptly, but they make a lot more noise or at least add a red `"Test Failed"`:

Out of memory in Java:
![image](https://user-images.githubusercontent.com/23709795/129539887-2985d8e8-4d90-46aa-bf71-4a082ffebea7.png)

Stack overflow in Java:
![image](https://user-images.githubusercontent.com/23709795/129538793-5fc025bc-ad07-4b4e-b8aa-05aa46044272.png)

Maybe it's just me not being familiar with all Codewars languages and only the ones I encountered report errors in a clearer way. But it's not the first time I see a user confused by lack of visible failure in Scala tests.

**Comment by kazk** [comment]
Good point, our ScalaTest reporter is pretty simple, so maybe it's missing some hook.

**Comment by kazk** [comment]
Added a handler for `RunAborted` hook. I'll close after deploying.

![image](https://user-images.githubusercontent.com/639336/129664026-0a6a2ed2-9ae4-42bb-9cc2-7911fe5b1659.png)
![image](https://user-images.githubusercontent.com/639336/129664435-d60f54d3-3edb-48d6-84cd-3a2af49eb293.png)
