### ISSUE TITLE
Calculation of time outs is NOT independent of server load

### ISSUE THREAD

**Issue by nomennescio** [codewars/runner#183]
When running time critical code, timing out happens often. However, this should be entirely dependent on the performance of the user's code. Currently however, it depends for a large part on the server load on CW.

Please calculate time outs such that it does not depend on server load, but on actual run time spent in user code.

**Comment by kazk** [comment]
> Currently however, it depends for a large part on the server load on CW.

We keep track of the load and various events/metrics like duration and timeouts. I don't see increased timeout rates when the load is higher. Durations look pretty consistent as well.

As far as I can tell, it's been performing consistent _enough_. When it doesn't seem like it, usually there are reasons, like entirely different inputs from random tests significantly affecting performance.

Maybe you can post a link to the kata you had experienced inconsistency.

> on actual run time spent in user code.

What do you mean by "user code"? If you mean just the solution, that's pretty much impossible because we're using test frameworks and tests written by users to run. The best you can do is to write test cases with shorter timeouts, which is usually better anyway because it can provide better feedback.

Also, the hard time limit must be for the total time (compile + test/run) because its main purpose is to limit the resource required for each submission. This won't change.

I'm closing this, but you are welcome to comment.

**Comment by Blind4Basics** [comment]
> https://www.codewars.com/kata/5b84d6d6b2f82f34d00000d7/python
>
> It might be that the variation in execution time might indeed be due to variation in random inputs that's causing a significant difference in processing time, I cannot tell.

I can tell you: that's uniquely a problem about the input generation, in that precise case.
