### ISSUE TITLE
Server execution error happens if Java file contains only record classes

### ISSUE THREAD

**Issue by FArekkusu** [codewars/runner#186]
As the title suggests, it is impossible to compile the code if any of the files contains `record`s but not `class`es. I haven't used this feature myself, so I can't tell if it's the correct behavior, but I suspect that it should work - I've created a repl on repl.it to test this out though, and there indeed were no problems.

You can create a kumite, paste `record MyRecord(int value) {}` into the solution box, press `RUN`, and see that it fails:

![image](https://user-images.githubusercontent.com/31668662/167172507-c168f8ff-7371-4eb7-91e5-6c889412fa04.png)

Judging by the way you get an error immediately after pressing `RUN`, it seems like it's caused by some preprocessor checking the files' contents before the actual compilation begins.

**Comment by hobovsky** [comment]
I think this may have something to do with the fact that runner needs to extract a name of the public class from source to save the file appropriately. The code for extracting the class name is probably just not prepared to not have a (public) class there.

Similar thing happens when you enter any gibberish into source, for example just `int test = 0;` etc.

**Comment by Madjosz** [comment]
According to Java Language Specification the file name of the *.java source file has to match the name of the public top level type (class, interface, enum and since JDK 16 also record) to compile. If the file only contains package private types, then the name can be arbitrary. To accomodate the frist rule CW runner tries to detect the name of the top level structure and name the file accordingly. `record` seems to be missing as allowed top level type.

**Comment by kazk** [comment]
Yeah, the runner tries to guess the correct file, and it's failing because it doesn't know about `record`.

**Comment by kazk** [comment]
Forgot to close this. This should be fixed.
