### ISSUE TITLE
Add Pascal

### ISSUE THREAD

**Issue by kazk** [codewars/runner#19]
- Name: Free Pascal
- Website: https://www.freepascal.org
- Language Version: [3.2.0](https://wiki.freepascal.org/FPC_New_Features_3.2.0)
- Test Framework: [FPTest](https://github.com/graemeg/fptest)

---

- [x] Install
- [x] Command to compile, run tests
- [x] Test Support (FPTest with [custom test runner/listener](https://github.com/codewars/fptest-codewars))
- [x] CodeMirror mode (built-in)
- [x] Icon

---

:+1: reaction _might_ help.

**Comment by pakLebah** [comment]
Free Pascal is now on version [3.2.0](https://wiki.freepascal.org/FPC_New_Features_3.2.0) since June 2020. Free Pascal also has an open source sister project that provides an advanced IDE written completely in Pascal with many component libraries for any kind of programming purposes, called [Lazarus IDE](https://www.lazarus-ide.org).

Free Pascal installation is pretty easy and straight forward. Most Pascal programmers simply install it from a ready to use binary installer for each kind of operating system. If you want to play around with the compiler's code, you could install it from source. The installation procedure is explained [here](https://wiki.freepascal.org/Installing_the_Free_Pascal_Compiler). 

Free Pascal has its own test frameworks called [FPTest](https://wiki.freepascal.org/FPTest) and [fpcUnit](https://wiki.freepascal.org/fpcunit). Free Pascal's wikipage has lots of information although some of them are a bit outdated. For more information about the development, you may want to subscribe to the [mailing lists](https://freepascal.org/maillist.html).

**Comment by kazk** [comment]
Thanks @pakLebah. We should be able to use [FPTest](https://github.com/graemeg/fptest) and use [`TestListener`](https://github.com/graemeg/fptest/blob/master/src/TestListenerIface.pas) to customize the output.

I might ask for your help once I start working on it.

**Comment by kazk** [comment]
@pakLebah Can you take a look at https://github.com/codewars/fptest-codewars and let me know what you think? [`example/`](https://github.com/codewars/fptest-codewars/tree/main/example) contains a project setup that I'm thinking of using.

**Comment by pakLebah** [comment]
@kazk: Well, except an error in epiktimer.pas because a missing `begin` inside a nested `$IFDEF` (at 419,5), I think the `challenge.lpr` works just fine. Here's the result:

```text
$ ./challenge

<DESCRIBE::>challenge
<DESCRIBE::>TExampleTests

<IT::>TestAdd
<PASSED::>Test Passed
<COMPLETEDIN::>0.0000

<IT::>TestBadAdd
<FAILED::>Expected:<:LF:>  "2"<:LF:>But was:<:LF:>  "0"
<COMPLETEDIN::>0.0000

<COMPLETEDIN::>0.0000
<COMPLETEDIN::>0.0000
```
Tested on masOS Mojave (darwin) using fpc v.3.2.0 64 bit.

**Comment by pakLebah** [comment]
I suggest you to use this configuration in the `fpc.cfg`:
```test
# Inherit from the defaults.
#INCLUDE /etc/fpc.cfg

# Default syntax settings
-S2chij-

# Include [fptest](https://github.com/graemeg/fptest) in the unit path.
-Fu../fptest/src
-Fu../fptest/3rdparty/epiktimer

# Include CodewarsTestRunner
-Fu../src

# Include solution and tests
-Fusrc
-Futests
```

**Comment by kazk** [comment]
Deployed. See https://github.com/codewars/codewars.com/wiki/Language-Pascal for how the test is set up and please let me know if you find any issues.
