### ISSUE TITLE
Can't find repo to fork to add features

### ISSUE THREAD

**Issue by andrewhbc** [codewars/runner#84]
**Describe the bug**
runner repo looks like it only contains the readme and templates and no longer contains the runner application.

**To Reproduce**
Logging into the github repo

**Expected behavior**
Being able to see the codebase

**Comment by kazk** [comment]
Please read the README:

![image](https://user-images.githubusercontent.com/639336/95927613-197e3100-0d74-11eb-81ec-404cadf07822.png)

---

The current CodeRunner takes a completely different approach from the old runner ([codewars-runner-cli](https://github.com/codewars/codewars-runner-cli)), so there's no "runner application" in images like before.

For contributing, we're open sourcing test runners and test reporters that's installed in the images so users can contribute there. See projects [with `code-runner` topic][code-runner-projects]. Please let me know if there's something that we haven't open sourced that you'd like to work on. There's also issues [with `help wanted` label][help-wanted].

We might open source `Dockerfile`s in the future as well, but this requires a lot of work because I need to redo the current automation setup and I don't have the time for it right now.

What do you want to add? Please open issues to discuss first, and we can work from there.

[help-wanted]: https://github.com/codewars/runner/issues?q=label%3A%22help+wanted%22+is%3Aissue+is%3Aopen+sort%3Aupdated-desc
[code-runner-projects]: https://github.com/search?q=topic%3Acode-runner+org%3Acodewars&type=Repositories
