### ISSUE TITLE
Add C# 10 (.NET 6 LTS)

### ISSUE THREAD

**Issue by thenuts** [codewars/runner#95]
Please complete the following information:

- Name: c#
- Version: 10
- Release Note/Changelog:
  - https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9
  - https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by suic86** [comment]
I would suggest updating other .NET languages (VB.NET, F#) to .NET 5 too.

**Comment by kazk** [comment]
Please open separate issues. F# may require significant effort because we're still using Mono there.

**Comment by suic86** [comment]
I'll create those issues tomorrow (if necessary). 

tl;dr

To provide some context: .NET 5 replaces .NET Core and the .NET Framework (Windows only), so Mono related code and .NET Core related code can be removed and replaced by .NET 5. It contains the latest version of all three languages (see [here](https://dotnet.microsoft.com/download/dotnet/5.0)).

Also PowerShell can be installed via `dotnet tool install --global PowerShell` once .NET Core or .NET 5 is installed. In theory, all 4 languages can be covered by a single docker image or two docker images (C#+F#+VB.NET and PowerShell) event. a dotnet5 image can be used as a source for all 4.

**Comment by kazk** [comment]
> In theory, all 4 languages can be covered by a single docker image or two docker images (C#+F#+VB.NET and PowerShell) event. a dotnet5 image can be used as a source for all 4.

I know. C#, VB.NET, and PowerShell are all _derived_ from the official .Net Core images already. In **practice**, for the runner's use case, having a single image containing multiple languages doesn't work well.

We have lots of demand for C#, so I'd like to support relatively up-to-date versions. But adding a new language version doesn't mean anything if it doesn't work with the existing contents. So, we update them and eventually remove the old image. If we had combined all languages together in a same image, we can't remove it until all of them are updated. Even when only one language is used, we'll be forced to continue paying for the cost of four (longer build/deploy, storage, confusing users by having many possible versions, etc). Languages that's not really popular tends to take much longer to update and this will force us to keep this huge image for a while.

There's not much benefit of having them in a single image either because a lot is already shared by deriving from the official image.

I wrote F# _may_ require significant effort because it's ancient (compatibility issues at code level) and requires a different way to compile and run test (Mono to .NET 5).

**Comment by suic86** [comment]
@kazk: I've created the two issues for VB.NET and F#.

Regarding your reply: I'm not going to argue with that as I don't know the implementation details of the current version(s) (AFAIK it's not opensource). I've based the idea on this [docker file](https://github.com/codewars/codewars-runner-cli/blob/master/docker/dotnet.docker) but it's apparently not relevant anymore.

**Comment by kazk** [comment]
Thanks. Yeah, that repository is irrelevant, and I archived it because it was confusing users.

The images are not open source, but they're publicly available as mentioned on `README`. Also, there's no `codewars-runner-cli` equivalent anymore, so what's not open source is just the `Dockerfile`s.

I've been thinking of making them open source just to make things more transparent, but I haven't got to it since it's not a priority, and I'll need to update the current automation setup.

**Comment by keithn** [comment]
any idea when this will happen? I've seen a bunch of people do some of these and can't use language features that are quickly becoming idiomatic C#, things like pattern matching.

**Comment by FArekkusu** [comment]
@kazk any updates on this request? You probably missed the comment above since you were away, and it'd be nice to know if there're any issues which make it impossible to migrate to C# 10.

**Comment by kazk** [comment]
I don't think so. I wanted to rewrite the test reporter to use events instead of transforming the XML output, but I haven't had the time to. But that shouldn't be a blocker.

**Comment by kazk** [comment]
Deployed

**Comment by kazk** [comment]
5 kata need to be updated. https://github.com/codewars/content-issues/wiki/List-of-C-Sharp-Kata-to-Update
