### ISSUE TITLE
Add F# 6.0 (.NET 6 LTS)

### ISSUE THREAD

**Issue by suic86** [codewars/runner#97]
Please complete the following information:

- Name: F#
- Version: 6.0 (.NET 6 LTS)
- Release Note/Changelog: https://github.com/dotnet/fsharp/blob/main/release-notes.md

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by hobovsky** [comment]
I am all for updating F#. Some time ago an F# translator asked me for help debugging an issue which turned out to be a difference in the behavior of new language version run locally, and old language version run on the CW runner.

**Comment by ihordyrman** [comment]
.NET 5.0 is not an LTS version and it will reach its end of support in a few months. 
Would be nice to see .NET 6 with F# 6.0 at codewars.

**Comment by kazk** [comment]
Yeah, I'd like to get F# updated. It's using the old Mono image, and have issues like #62.

If you'd like to help, create a repository with a minimal F# project with tests. Then either implement [custom test reporter](https://github.com/codewars/runner/blob/main/docs/messages.md), or find how it can be done. Document everything.
I'm open to using a different test framework too if there's something more popular, and easy to work with. It's going to be a breaking change, and we don't have that many F# kata, so let's use this opportunity to improve it.

**Comment by jhurdlow** [comment]
Really need this one. Have a perfectly working solution to a Kata running in Visual Studio (F# 7) , but the ancient version of F# (4.1) running in CodeWars gives a useless compilation error. Clearly something has changed in the language and I'm using that thing. Not even clear how to refactor to get working. :(

**Comment by ihordyrman** [comment]
@kazk you can use the same framework as for C#. There is no need to invent something new.
.NET ecosystem already contains various frameworks for testing that can be used both with C# and F#.
The most popular is [xUnit](https://github.com/xunit/xunit). [FsUnit](https://github.com/fsprojects/FsUnit) can also provide some helpful functions and make tests more readable. 

I've tried to look into open repositories and found some useful examples.

https://github.com/adbi13/SortingAlgorithms/tree/main/Tests
https://github.com/fsprojects/FsUnit/tree/master/tests/FsUnit.Xunit.Test
https://nabeelvalley.co.za/blog/2021/10-04/xunit-with-fsharp/
https://khalidabuhakmeh.com/write-unit-tests-with-fsharp-and-xunit

I'll be glad to help you with updating. Let me know if I can do something to make updating process faster.

**Comment by hobovsky** [comment]
kazk please correct me in any place I am wrong: regarding the update of F# on Codewars, the situation is as follows:

Currently, F# on Codewars uses Fuchu framework which seems to be not supported anymore. Kazk's idea was to replace Fuchu with:
1. something what F# programmers would find natural,
1, something what would nicely support Codewars' format of test output.

Ad 1.: the idea is to make the work with F# feel "natural" for F# developers. The problem is, I am not sure what testing framework is considered "usual" in F# projects. Is it NUnit? Or maybe xUnit? Maybe something else? I tried to create an NUnit test reported for Codewars, but this brings us to the next point...

Ad 2.: problem with NUnit is that it does not play well with the way how Codewars runner expects the output to be presented. The output is expected to be sent to stdout in a particular format, and it was difficult for me to make NUnit work with stdout. There's a lot of redirections and interceptions happening, and making teests and user solution be able to work with stdout turns out to be difficult.  
Another option is to grab the NUnit XML report and transform it to the format expected by Codewars runner. This is how C# setup works today, but its disadvantage is that it works only when the report file is created. If tests crash or time out, there's no report file and Codewars cannot present partial results of tests.

I tried to experiment a bit in this area, but the problem is that I am not really familiar with "real" F# projects, and after lack of initial progress, I postponed the topic and left it for future. I invited you to my private repository where you can find some (not much) code I created when working on the reporter.
If you'd be interested in helping or taking over the topic, let me know here or poke me on Codewars Discord and I can share more details.

**Comment by ihordyrman** [comment]
@hobovsky thanks. I will look at this repo soon.
I'm not an F# expert, but I know the language and .NET ecosystem. Anyway, I think we will figure out how to make it work.

**Comment by kazk** [comment]
Deployed. Thanks @hobovsky for your help.

F# 6.0 uses NUnit to test instead of Fuchu, and we no longer concatenate files. This obviously requires updating manually, so please help. If you want to see how the test is executed, see https://github.com/codewars/fsharp. `dotnet run` is currently used, but I'm reconsidering using the compiler directly like C# because it seems much slower than I thought.
